spring:
  datasource:
    # 账号配置
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useUnicode=true&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 测试环境特定的配置覆盖
      initial-size: 3
      min-idle: 3
      max-active: 10
      # 禁用测试环境的监控页面
      stat-view-servlet:
        enabled: false
        login-username: admin
        login-password: acyddseieiw24
      web-stat-filter:
        enabled: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DB}
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位

swagger:
  enabled: true

logging:
  file: /data/logs

sms:
  message:
    accessToken: xxx

tm:
  brands:
    - name: xxx
      accountId: xxx
      channelId: xxx
      token: xxx
  # 用户相关接口
  member:
    get: https://xxx
    updateUrl: https://xxx
    registerUrl: https://xxx
  # 短信发送配置
  sms:
    send: https://xxx
  # 事件上报配置
  event:
    report: https://xxx
  # TensorFlow服务url配置
  tensorFlow:
    v1:
      color: https://xxx
    v2:
      diaper: https://xxx
      color: https://xxx
      stool: https://xxx
    v3:
      diaper: https://xxx
      color: https://xxx
      stool: https://xxx