app:
  name: chy-boot-rest-api

spring:
  application:
    name: chy-boot
  profiles:
    active: ${profile.id:local}
  # 数据库连接池配置
  datasource:
    dynamic:
      primary: master
      # 使用Hikari作为默认连接池
      hikari:
        # 连接池最大连接数
        maximum-pool-size: 20
        # 最小空闲连接数
        minimum-idle: 5
        # 空闲连接存活最大时间（毫秒）
        idle-timeout: 600000
        # 连接最大存活时间（毫秒）
        max-lifetime: 1800000
        # 连接超时时间（毫秒）
        connection-timeout: 30000
        # 测试连接是否可用的查询语句
        connection-test-query: SELECT 1
        # 连接池名称
        pool-name: HikariCP-Pool
        # 自动提交
        auto-commit: true
        # 验证超时（毫秒）
        validation-timeout: 5000
        # 注册MBeans
        register-mbeans: true

server:
  compression:
    enabled: true
  port: 8084
  undertow:
    buffer-size: 1024
    direct-buffers: true
    io-threads: 8
    worker-threads: 400
  tomcat:
    max-connections: 10000
    max-threads: 200
    min-spare-threads: 10
    accesslog:
      enabled: true
      directory: logs
      pattern: '%t %a "%r" %s %b %D %I'
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      rotate: true

# 启动上下文过滤器
web:
  execute:
    context:
      enabled: true  # 启用统一的请求上下文处理器

# XSS过滤器配置
cy:
  xss:
    enable: true
    # 跳过的URL路径
    skip-url:
      - /api/v1/upload/**
    # URL排除模式
    url:
      exclude-patterns:
        - /swagger-ui/**
        - /v3/api-docs/**

management:
  health:
    redis:
      enabled: false
  endpoint:
    health:
      # always、when-authorized、never，默认值是never
      show-details: when_authorized
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,caches,loggers
      base-path: /actuator
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.9, 0.95, 0.99
      sla:
        http.server.requests: 100ms, 500ms, 1s, 5s

sms:
  message:
    code: 您的验证码是{0}。如非本人操作，请忽略本短信

# Caffeine缓存统计
caffeine:
  stats:
    enabled: true