spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/chy-boot?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useUnicode=true&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    cluster:
      nodes:
        - 127.0.0.1:6371
      max-redirects: 5

swagger:
  enabled: true

sms:
  message:
    accessToken: xxx

tm:
  brands:
    - name: xxx
      accountId: xxx
      channelId: xxx
      token: xxx
  # 用户相关接口
  member:
    get: https://xxx
    updateUrl: https://xxx
    registerUrl: https://xxx
  # 短信发送配置
  sms:
    send: https://xxx
  # 事件上报配置
  event:
    report: https://xxx
  # TensorFlow服务url配置
  tensorFlow:
    v1:
      color: https://xxx
    v2:
      diaper: https://xxx
      color: https://xxx
      stool: https://xxx
    v3:
      diaper: https://xxx
      color: https://xxx
      stool: https://xxx

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    com.baomidou.dynamic: debug

test:
  baseUrl: https://v1.hitokoto.cn/
  accessKeyId: sdfsdfdsf
  accessKeySecret: sadfsadfsdfsdf
  authUri: http://localhost:8085/