#!/bin/bash -e

JAVA_OPTS="${JAVA_OPTS} \
  ${JAVA_JMX_EXPORTER_AGENT} \
  -server \
  -Xms${JAVA_XMS}m \
  -Xmx${JAVA_XMX}m \
  -Xss512k \
  -XX:NewRatio=2 \
  -XX:+UseConcMarkSweepGC \
  -XX:+CMSClassUnloadingEnabled \
  -XX:CMSInitiatingOccupancyFraction=70 \
  -XX:SoftRefLRUPolicyMSPerMB=0 \
  -XX:MaxTenuringThreshold=7 \
  -XX:+UseCMSInitiatingOccupancyOnly \
  -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses \
  -XX:GCTimeRatio=19 \
  -Xnoclassgc \
  -XX:+HeapDumpOnOutOfMemoryError \
  -XX:HeapDumpPath=/srv/stooltracker-backend/logs/jvm \
  -XX:+PrintGCDetails \
  -XX:+PrintGCDateStamps \
  -XX:+UseGCLogFileRotation \
  -XX:NumberOfGCLogFiles=8 \
  -XX:GCLogFileSize=100M \
  -Xloggc:/srv/stooltracker-backend/logs/stooltracker-backend.log \
  -Duser.timezone=GMT+08 \
  -Djava.security.egd=file:/dev/./urandom"

echo "java ${JAVA_OPTS} -jar /srv/stooltracker-backend/stooltracker-backend.jar"
exec java ${JAVA_OPTS} -jar /srv/stooltracker-backend/stooltracker-backend.jar
